Add retry option to deployed services
eclipse-xpanse/xpanse-ui pull request #1025
Opened 2024-07-29 09:24 UTC by WangLiNaruto

Fixed #eclipse-xpanse/xpanse#1694

2024-07-29 15:49 UTC, swaroopar requested changes

2024-07-29 15:49 UTC, swaroopar commented on src/components/content/order/create/OrderSubmit.tsx
> +    const getReDeployLatestServiceOrderStatusQuery = useLatestServiceOrderStatusQuery(
would it be possible to have just one query for both cases?
Ideally the old query must be automatically replaced with new one as soon as the ID is replaced with  new order ID.

2024-07-29 15:49 UTC, swaroopar commented on src/components/content/order/orderStatus/OrderSubmitStatusAlert.tsx
> +    optionType,
we do not need this extra field. 
The deployment properties must be taken from the old service. The order status service will only return the status of the order. No information about the service.

2024-07-30 09:04 UTC, swaroopar requested changes

2024-08-01 08:54 UTC, baixinsui commented
LGTM

2024-08-05 02:55 UTC, dengyali0125 commented
LGTM

2024-08-07 01:14 UTC, dengyali0125 commented
LGTM

2024-08-12 11:48 UTC, swaroopar approved these changes
LGTM

2024-08-12 11:48 UTC, merged