Order screen overlapping fields on smaller screens
eclipse-xpanse/xpanse-ui pull request #1071
Opened 2024-08-13 03:30 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#1857
![image](https://github.com/user-attachments/assets/838be0ca-ec68-4049-b504-89c13f30db2d)

2024-08-13 06:34 UTC, baixinsui commented
LGTM

2024-08-14 10:27 UTC, swaroopar requested changes

2024-08-14 10:27 UTC, swaroopar commented on src/components/content/order/common/BillingModeSelection.tsx
> +            <Col xs={24} sm={12} md={16} lg={8} xl={5}>
would avoid such logic here. Better to use only responsive design

2024-08-15 08:02 UTC, dengyali0125 commented
LGTM

2024-08-19 08:06 UTC, swaroopar approved these changes

2024-08-19 08:08 UTC, merged