show billingmode and region for myservices table.
eclipse-xpanse/xpanse-ui pull request #1136
Opened 2024-09-09 07:09 UTC by Alice1319

fixed eclipse-xpanse/xpanse #1900

2024-09-09 08:38 UTC, dengyali0125 commented
LGTM

2024-09-09 09:57 UTC, swaroopar requested changes

2024-09-09 09:57 UTC, swaroopar commented on src/components/content/deployedServices/common/DeployedBillingMode.tsx
> +                        {currentBillingMode.valueOf()}
tag color is same as ServiceHostedBy field. Please keep the colors unique

2024-09-09 09:57 UTC, swaroopar commented on src/components/content/deployedServices/common/DeployedRegion.tsx
> +                {currentRegion.area + '(' + currentRegion.name + currentRegion.site + ')'}
Just the below is enough. 
regionname (site - sitename)

2024-09-10 07:40 UTC, swaroopar approved these changes

2024-09-10 07:40 UTC, merged