add config parameters list to service catalog display
eclipse-xpanse/xpanse-ui pull request #1228
Opened 2024-10-18 09:15 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#1972

ISV
![image](https://github.com/user-attachments/assets/4bc86134-96de-42e7-becd-586e19f96b7f)
![image](https://github.com/user-attachments/assets/3b107448-82d1-48ea-83c9-dad628814952)
![image](https://github.com/user-attachments/assets/f197072c-4e60-488e-9392-8f09024b17d3)

CSP
![image](https://github.com/user-attachments/assets/fb603191-20f5-4c40-8d8f-79eb79c6067c)
![image](https://github.com/user-attachments/assets/cf3461c1-9afe-45f8-a4fb-0b866c6aecbf)

2024-10-18 13:30 UTC, swaroopar requested changes

2024-10-18 13:30 UTC, swaroopar commented on src/components/content/deployServiceConfigParameter/DeploymentServiceConfigurationParameter.tsx
> +            title: <div className={deploymentVariablesStyles.variablesColumns}>Value</div>,
we can remove the value column.  It is not necessary.

2024-10-18 13:30 UTC, swaroopar commented on src/components/content/common/ocl/DisplayOclData.tsx
>                          <FlavorsText flavors={ocl.flavors.serviceFlavors} />
i think it is better we move the flavors above Deployment variables and configuration parameters. otherwise the flavors are kind of lost.

2024-10-18 13:41 UTC, swaroopar requested changes

2024-10-18 13:41 UTC, swaroopar commented on src/components/content/deployServiceConfigParameter/DeploymentServiceConfigurationParameter.tsx
> +                <Table
is it possible to fit the table within the space available without any scrollbar? Looks a bit odd with the scroll bar. Please see if antd component provides a way to configure this.

2024-10-21 03:24 UTC, Alice1319 commented
LGTM

2024-10-21 04:37 UTC, swaroopar requested changes

2024-10-21 04:37 UTC, swaroopar commented on src/components/content/deployServiceConfigParameter/DeploymentServiceConfigurationParameter.tsx
> +                <Table
is this solved?

2024-10-21 04:37 UTC, swaroopar commented on src/components/content/common/ocl/DisplayOclData.tsx
> +                        {ocl.serviceConfigurationManage?.configurationParameters ? (
we need to show an empty table if the configuration is empty.

2024-10-21 04:37 UTC, swaroopar commented on src/components/content/deployServiceConfigParameter/DeploymentServiceConfigurationParameter.tsx
> +                    loading={parameters.length <= 0}
this loading is not correct.
I see it is wrong in the `DeploymentVariables` component as well. 
It must be based on the API call status and nothing else. 
If there is no need of a loading state, you can just remove it as well.

2024-10-21 08:56 UTC, swaroopar approved these changes
LGTM

2024-10-21 08:56 UTC, merged