add service configuration option to myservices
eclipse-xpanse/xpanse-ui pull request #1238
Opened 2024-10-23 03:14 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#1975

![image](https://github.com/user-attachments/assets/b8e00f74-1b23-4c15-a3e9-96a477fe8b3d)

2024-10-23 06:35 UTC, swaroopar requested changes

2024-10-23 06:35 UTC, swaroopar commented on src/components/content/order/serviceConfiguration/CurrentServiceConfiguration.tsx
> +                            <Input name={'ServiceId'} defaultValue={serviceConfigurationDetails.serviceId} />
we can remove the serviceId field

2024-10-23 06:35 UTC, swaroopar commented on src/components/content/order/serviceConfiguration/CurrentServiceConfiguration.tsx
> +                            <Input name={'CreatedTime'} defaultValue={serviceConfigurationDetails.updatedTime} />
we do not need this as well.

2024-10-23 06:35 UTC, swaroopar commented on src/components/content/order/serviceConfiguration/CurrentServiceConfiguration.tsx
> +                                        {'UpdatedTime'}
we can just use this time step. but rename the field to 'Config Last Updated At'

2024-10-23 06:35 UTC, swaroopar commented on src/components/content/order/serviceConfiguration/CurrentServiceConfiguration.tsx
> +        return param?.description ?? key;
instead of returning the key -> we can return 'No description available'

2024-10-24 08:50 UTC, Alice1319 commented
LGTM

2024-10-24 09:31 UTC, closed without merging