Changes to review service of CSP
eclipse-xpanse/xpanse-ui pull request #1361
Opened 2024-12-13 02:44 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#2112

2024-12-13 03:06 UTC, Alice1319 commented
LGTM

2024-12-13 03:09 UTC, yuanxiaojun987 commented
LGTM

2024-12-13 03:09 UTC, luoping-12345 commented
LGTM

2024-12-13 03:10 UTC, profoundwu commented
LGTM

2024-12-14 15:49 UTC, swaroopar requested changes
looks good. just one small change required.

2024-12-14 15:49 UTC, swaroopar commented on src/components/content/deployedServices/common/DeployedServicesHostingType.tsx
> +    currentServiceHostingType: 'self' | 'service-vendor';
we must not define the types again. we must read the values only from the API generated classes.

2024-12-16 03:28 UTC, closed without merging