update api calling and purge service state alert.
eclipse-xpanse/xpanse-ui pull request #1392
Opened 2024-12-30 08:20 UTC by Alice1319

2024-12-30 09:02 UTC, WangLiNaruto commented
LGTM

2024-12-30 09:10 UTC, profoundwu commented
LGTM

2024-12-30 11:48 UTC, baixinsui commented
LGTM

2024-12-31 09:14 UTC, swaroopar requested changes
the myservices 'details' option is still triggering a wrong API call

2024-12-31 09:52 UTC, swaroopar requested changes

2024-12-31 09:52 UTC, swaroopar commented on src/components/content/deployedServices/common/DeployedServicesDetailsContent.tsx
> +    const getOrderableServiceDetails = useGetOrderableServiceDetailsQuery(serviceId);
better we rename this method to 'useGetOrderableServiceDetailsByServiceIdQuery'

2025-01-02 02:04 UTC, Alice1319 commented on src/components/content/deployedServices/common/DeployedServicesDetailsContent.tsx
> +    const getOrderableServiceDetails = useGetOrderableServiceDetailsQuery(serviceId);
fixed.

2025-01-02 05:37 UTC, swaroopar approved these changes
LGTM

2025-01-02 05:37 UTC, merged