Feature/service order default version
eclipse-xpanse/xpanse-ui pull request #16
Opened 2023-03-28 01:09 UTC by WangLiNaruto

2023-03-28 06:13 UTC, iskey commented on src/components/content/order/Services.tsx
> +                        defaultVersion: item.versions.sort((v1, v2) => {
can we refine the version sort? it seems v1.9 is newer than v.1.10 by this implementation.

2023-03-28 06:15 UTC, iskey commented on src/components/content/order/Services.tsx
> +    const onClicked = function (cfg: string, defaultVersion: string) {
also, is it better to rename the defaultVersion to latestVersion?

2023-03-28 06:20 UTC, iskey requested changes
comments added.

2023-03-29 07:11 UTC, iskey commented
conflicts must be resolved.

2023-03-29 07:51 UTC, iskey commented on src/styles/service_order.css
> +    padding: 0px;
`px` is not needed here.

2023-03-29 07:51 UTC, iskey commented on src/styles/service_order.css
> +    padding: 0px;
ditto

2023-03-29 07:52 UTC, iskey commented on src/styles/service_order.css
> +    padding: 0px;
doitto.

2023-03-29 08:28 UTC, iskey commented on src/styles/service_order.css
> +.services-content-body-space {
I think the `submit-alert-tip` should be kept.

2023-03-30 02:10 UTC, WangLiNaruto commented
![image](https://user-images.githubusercontent.com/122504203/228709915-fc37ac96-9665-4d20-9c72-27cf06a55650.png)

2023-03-30 02:27 UTC, iskey approved these changes
looks good.

2023-03-30 02:27 UTC, merged