update form rules.
eclipse-xpanse/xpanse-ui pull request #231
Opened 2023-10-16 10:34 UTC by Alice1319

fixes eclipse-xpanse/xpanse #902
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/42802200/74cd023f-7796-414d-9b5c-656ba833280d)

2023-10-16 10:53 UTC, swaroopar requested changes

2023-10-16 10:53 UTC, swaroopar commented on src/components/content/order/formElements/NumberInput.tsx
> +            return Promise.reject(new Error(`The new password not match minimum ${minimum}!`));
it is not always a password field. We need a better error message here.
`Value does not satisfy criteria minimum ${minimum}`

2023-10-16 10:53 UTC, swaroopar commented on src/components/content/order/formElements/NumberInput.tsx
> +            return Promise.reject(new Error(`The new password not match maximum ${maximum}!`));
`Value does not satisfy criteria maxinum ${maximum}`

2023-10-16 10:53 UTC, swaroopar commented on src/components/content/order/formElements/NumberInput.tsx
> +        return Promise.reject(new Error('The new password that you entered do not match!'));
not a valid condition at all.

2023-10-16 10:53 UTC, swaroopar commented on src/components/content/order/formElements/NumberInput.tsx
> +        if (key === 'minimum' || key === 'maximum') {
can you please define a new enum type which has all supported json schema keys.. and then use it here. 
enum must have minimum, maximum, minimumLength, etc.. as allowed values.

2023-10-16 10:53 UTC, swaroopar commented on src/components/content/order/formElements/SelectField.tsx
> +    const activeCspList: CredentialVariables.csp[] = [
please remove this definition of eum here again. 
Also the selectField must handle any enum values. Not just Csp

2023-10-16 10:53 UTC, swaroopar commented on src/components/content/order/formElements/TextInput.tsx
> +            return Promise.reject(new Error(`The new password not match the pattern!${regExp}`));
error text  is not correct. Better we execute each rule separately and return separate errors for minLength, maxLength and pattern.

2023-10-18 18:23 UTC, swaroopar requested changes

2023-10-18 18:23 UTC, swaroopar commented on src/components/content/order/formElements/TextInput.tsx
> +            return Promise.reject(new Error(`The new password not match the pattern!${regExp}`));
also there should be space beween pattern! and the regExp

2023-10-18 18:23 UTC, swaroopar commented on src/components/content/order/formElements/NumberInput.tsx
> +            return Promise.reject(new Error(`Value does not satisfy criteria minimum ${minimum}!`));
currently the error is shown multiple times.. also has some "undefined" error.

![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/e7a4aeea-3906-4c9e-9763-00877c7b16c4)

2023-10-19 03:24 UTC, Alice1319 commented on src/components/content/order/formElements/CommonTypes.ts
> +    valueSchema: Record<string, Record<string, unknown>> | undefined;
of course, we can do it

2023-10-19 11:24 UTC, closed without merging