Refactor the migration pages
eclipse-xpanse/xpanse-ui pull request #244
Opened 2023-10-31 09:06 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#945
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/2eaf0a08-a5b5-4a3b-ac32-02f6fc95ff6d)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/f7dc9b2d-cdeb-4892-b79c-5f7789cac57b)

2023-10-31 11:10 UTC, swaroopar requested changes

2023-11-01 05:01 UTC, swaroopar requested changes
@WangLiNaruto i just set the old comments to unresolved where the fixes are not there yet. 
If possible, pls also update the screenshots.

2023-11-01 07:23 UTC, WangLiNaruto commented on src/components/content/order/formElements/CommonTypes.ts
>  export enum MigrationStatus {
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/07c57da5-20c4-4a8b-91af-db19ff61518d)

2023-11-02 05:03 UTC, swaroopar approved these changes
LGTM

2023-11-02 05:03 UTC, merged