Enable operation 'details' when service state is `deploy failed`
eclipse-xpanse/xpanse-ui pull request #456
Opened 2024-01-30 10:50 UTC by baixinsui

fixes https://github.com/eclipse-xpanse/xpanse/issues/1301

2024-01-30 13:24 UTC, swaroopar requested changes

2024-01-30 13:24 UTC, swaroopar commented on src/components/content/deployedServices/myServices/MyServices.tsx
> +                    record.serviceDeploymentState === DeployedService.serviceDeploymentState.DESTROY_SUCCESSFUL ? (
@baixinsui Actually the condition was added incorrectly and i had requested him to open a PR to rollback this wrong fix. Its better if you revert this complete commit from him with your PR. Thank you

https://github.com/eclipse-xpanse/xpanse-ui/pull/364/files

2024-01-31 03:48 UTC, swaroopar requested changes

2024-01-31 03:48 UTC, swaroopar commented on src/components/content/deployedServices/myServices/MyServices.tsx
> +                    record.serviceDeploymentState === DeployedService.serviceDeploymentState.DESTROY_SUCCESSFUL ? (
@baixinsui we must remove this full condition itself - whatever that was added in PR-364. It was completely wrong. 
the actual requirement was to disable details button for other conditions and this user story is still open.

2024-01-31 06:43 UTC, baixinsui commented
Related requirement in the issue https://github.com/eclipse-xpanse/xpanse/issues/1171.

2024-01-31 06:43 UTC, closed without merging