add Warning for Modify and Scale.
eclipse-xpanse/xpanse-ui pull request #794
Opened 2024-05-16 07:47 UTC by Alice1319

fixes eclipse-xpanse/xpanse#1586

2024-05-16 09:16 UTC, WangLiNaruto commented
LGTM

2024-05-16 10:32 UTC, swaroopar commented on src/components/content/order/common/utils/ScaleOrModifyWarnings.tsx
> +const ChangeFlavorAndPropertyCauseDataWillBeLost: string = `Changing flavor and service property %s will cause service to be restarted and data to be lost. Proceed?`;
here also should we have `properties` instead of just `property`?

2024-05-16 10:33 UTC, swaroopar requested changes

2024-05-16 10:33 UTC, swaroopar commented on src/components/content/order/modify/Modify.tsx
> +                            okText='Yes'
default selection should be "no"

2024-05-16 10:54 UTC, swaroopar requested changes

2024-05-16 10:54 UTC, swaroopar commented on src/components/content/order/modify/Modify.tsx
> +                            title='Scale'
title should be different?

2024-05-16 10:54 UTC, swaroopar commented on src/components/content/order/modify/Modify.tsx
> +                        <Popconfirm
can we make the warning icon in red color?

2024-05-16 12:42 UTC, swaroopar requested changes

2024-05-16 12:42 UTC, swaroopar commented on src/components/content/order/common/utils/ScaleOrModifyWarnings.tsx
> +        findModifiedProperties(initialDeployParams, deployParamsCache).length < 2
we must remove this logic. Very hard to understand. 
Instead need a separate method to figure out if flavor is only changing or flavor + properties are changing.

2024-05-16 12:42 UTC, swaroopar commented on src/components/content/order/common/utils/ScaleOrModifyWarnings.tsx
> +const getModifiedPropertiesTip = (
logic should be entirely based on the ModificationImpact flags. 
Check if property has changed. Check that specific property's modification impact flags. 
Check if flavor change is requested. Check that service's OCL to find out the impact of flavor change,

2024-05-17 08:23 UTC, swaroopar requested changes

2024-05-17 08:23 UTC, swaroopar commented on src/components/content/order/scale/Scale.tsx
> +        if (getModificationImpact) {
do we need this check? this is a mandatory field. so the property will exist always.

2024-05-17 08:23 UTC, swaroopar commented on src/components/content/order/modify/Modify.tsx
> +    function getModifiedProperties(
we must check the ModificationImpact of each DeployVariable.

2024-05-21 09:15 UTC, swaroopar reviewed
LGTM

2024-05-21 09:16 UTC, swaroopar approved these changes

2024-05-21 09:17 UTC, merged