update service state update tasks to async APIs
eclipse-xpanse/xpanse-ui pull request #807
Opened 2024-05-21 12:05 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#1613
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/a4ae8044-022d-4dbd-8e75-1af6057a8d09)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/b740a04d-afac-4b0a-b6d2-8682ab02b533)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/53e498a4-86b6-4cf2-893e-dda223ca2ec5)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/8f80ae18-d0d3-4970-a939-1bb896e3a129)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/55ab0b57-11d0-4fa0-8fb5-70cb47d7d8c8)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/4a3cdfc2-c39c-4026-ae24-164e51c9bc20)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/abd5eb4a-43f1-4e7f-9fca-3380499d9bc8)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/ed7744a6-38f1-46f3-a65f-27204672fdf2)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/cddc2005-7ed2-43ae-83c2-0b3552c00b0a)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/812a20a2-62d6-4810-b107-5c421f43a2f4)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/02e70d82-c2ee-418d-b7db-6a5c4f9edbc6)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/44f6300d-2e84-46e9-b38b-88ccf8700480)

2024-05-22 02:38 UTC, Alice1319 commented
LGTM

2024-05-22 13:28 UTC, swaroopar requested changes

2024-05-22 13:28 UTC, swaroopar commented on src/components/content/order/serviceState/stop/StopServiceStatusAlert.tsx
> +                    description={<OrderSubmitResultDetails msg={'Stop request failed'} uuid={deployedService.id} />}
msg - Service stop request failed

2024-05-22 13:28 UTC, swaroopar commented on src/components/content/order/serviceState/stop/StopServiceStatusAlert.tsx
> +                            <OrderSubmitResultDetails msg={'Service stop successfully'} uuid={deployedService.id} />
msg - Service stopped successfully

2024-05-22 13:28 UTC, swaroopar commented on src/components/content/order/serviceState/restart/RestartServiceStatusAlert.tsx
> +                            <OrderSubmitResultDetails msg={'Service restart successfully'} uuid={deployedService.id} />
msg - Service restarted successfully

2024-05-22 13:28 UTC, swaroopar commented on src/components/content/order/serviceState/start/StartServiceStatusAlert.tsx
> +                            <OrderSubmitResultDetails msg={'Service start successfully'} uuid={deployedService.id} />
msg - Service started successfully

2024-05-27 14:32 UTC, swaroopar requested changes

2024-05-27 14:32 UTC, swaroopar commented on src/components/content/order/serviceState/restart/RestartServiceStatusAlert.tsx
> +            <div className={'submit-alert-tip'}>
we must migrate all CSS classes to use CSS Modules. Please refer to other classes which are already using it. or JinPing can also help you with it.

2024-05-27 14:32 UTC, swaroopar commented on src/components/content/order/serviceState/restart/RestartServiceStatusAlert.tsx
> +            <div className={'submit-alert-tip'}>
no space between alert and the button below. Please make it consistent with all other alerts in the myservices UI.

![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/b29faf51-be61-40ee-bc41-b8bd7788ed9f)

2024-05-28 07:05 UTC, swaroopar approved these changes
LGTM

2024-05-28 07:05 UTC, merged