display features.
eclipse-xpanse/xpanse-ui pull request #818
Opened 2024-05-24 07:53 UTC by Alice1319

2024-05-27 10:09 UTC, swaroopar requested changes

2024-05-27 10:09 UTC, swaroopar commented on src/components/content/order/common/FlavorInfo.tsx
> +    const [maxFeatures, setMaxFeatures] = useState<number>(0);
@Alice1319 why do we need this?

2024-05-27 10:09 UTC, swaroopar commented on src/components/content/order/common/FlavorInfo.tsx
> +                                                    {(20).toString().concat(' ').concat('CNY/').concat('hourly')}
Please keep currency "EUR" as the default

2024-05-27 10:09 UTC, swaroopar commented on src/components/content/order/scale/Scale.tsx
> +    const getFlavorContent = (flavor: ServiceFlavor): React.JSX.Element => {
everything here seems to be duplicate of what we have in FlavorInfo.tsx. Please remove any duplicate code.

2024-05-27 10:09 UTC, swaroopar commented on src/components/content/order/scale/Scale.tsx
> +        return <span className={'flavor-card-title'}>{title}</span>;
use CssModule

2024-05-27 11:56 UTC, Alice1319 commented on src/components/content/order/common/FlavorInfo.tsx
> +    const [maxFeatures, setMaxFeatures] = useState<number>(0);
add a comment.

2024-05-28 11:14 UTC, WangLiNaruto commented
LGTM

2024-05-28 13:01 UTC, swaroopar requested changes

2024-05-28 13:01 UTC, swaroopar commented on src/components/content/order/formDataHelpers/flavorHelper.ts
> +export const getMaxFeatureBoxSize = (flavorList: ServiceFlavor[] | undefined): number => {
we must still get rid of all this.

2024-05-29 12:12 UTC, swaroopar requested changes
LGTM

2024-05-29 12:13 UTC, swaroopar approved these changes
LGTM

2024-05-29 12:14 UTC, merged