add re-regsiter and delete options to service catalog
eclipse-xpanse/xpanse-ui pull request #845
Opened 2024-06-03 11:24 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#1655
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/2d87a941-3c93-4613-9614-da131a4343c2)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/0d1737a7-655b-4c3e-b5d3-5ff4c6624272)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/07077697-fd36-4a8c-97f6-41c950ba136b)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/4f335735-a067-41b5-841e-aa4f2fa9af34)
![image](https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/25f8225d-e1b5-461e-ab32-d5c81bcecb99)

2024-06-03 13:53 UTC, swaroopar requested changes

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/re-register/reRegisterService.tsx
> +                        serviceRegistrationState !== ServiceTemplateDetailVo.serviceRegistrationState.UNREGISTERED
in the screenshots, i see that the button is enabled even after the re-register request is submitted. The button must be disabled, if the re-register is submitted.

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/delete/DeleteService.tsx
> +                <Button
same here. the delete button is enabled even after the delete is successful.

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/delete/DeleteResult.tsx
> +                    message='Service Delete Successfully'
should be `Service Deleted Successfully`

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/delete/DeleteResult.tsx
> +                    description={'Service Delete successfully.'}
description can be something else - Service removed from the database completely.

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/re-register/reRegisterResult.tsx
> +                    message='Service Re-Register Successfully'
Service re-registered successfully

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/re-register/reRegisterResult.tsx
> +                    description={'Service submitted for review successfully.'}
Service submitted for review of cloud provider.

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/unregister/UnregisterResult.tsx
> +                    description={'Service removed from the catalog successfully.'}
the earlier description was fine. No need to change that

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/unregister/UnregisterResult.tsx
> +    if (
is it necessary to change this if condition ?
It must work just with the old condition.

2024-06-03 13:53 UTC, swaroopar commented on src/components/content/catalog/services/delete/DeleteResult.tsx
> +    if (
should we enough just to check the deleteRequestState.

2024-06-04 06:46 UTC, Alice1319 commented
LGTM

2024-06-05 08:29 UTC, swaroopar approved these changes
LGTM

2024-06-05 08:29 UTC, merged